### PR TITLE
Add nginx restart recipe

### PR DESCRIPTION
**Pull request by swrobel**
As recommended by Jonathan@AWS https://forums.aws.amazon.com/message.jspa?messageID=536357

Should be safe to merge into master-chef-11.10 as well

My contribution is provided under the Apache 2.0 license.

### CODE REVIEW

**Comment by cbbarclay** [comment]
Thank you, we will review your pull request.

**Comment by githuesch** [comment]
I think it would be confusing to add this recipe without using it. You can trigger a restart of your app servers in the console and through the API, and the recipe that is executed for Rails apps is https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/deploy/recipes/rails-restart.rb.

I'm not saying that having a separate recipe to restart nginx is a bad thing, not at all. If we include this one, there should also be one for Apache. But again, we would have to include that recipe instead of executing `node[:opsworks][:rails_stack][:restart_command]`, which is the current behavior.

**Comment by githuesch** [comment]
@swrobel Are you using nginx with static apps or with Rails apps?

**Comment by githuesch** [comment]
@swrobel I was asking because there is also https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/deploy/recipes/web-restart.rb for static web apps.

The main difference between this one and the one @jweiss gave you is that it effectively only executes for static apps.

**Comment by swrobel** [comment]
I'm using Rails, but the rails-restart command, as far as I can tell, does not restart nginx. This recipe became necessary when the heartbleed bug occurred and we had to update_dependencies, but that only installed the new nginx, it didn't issue the restart so that it was used.

**Comment by githuesch** [comment]
Gotcha. Maybe we just drop the `if` clause from https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/deploy/recipes/web-restart.rb and use that one instead of adding a recipe that does almost the same thing.

**Comment by swrobel** [comment]
Sounds good to me. I guess that doesn't solve the Apache issue, but I don't use Apache so I haven't looked into it.

**Comment by githuesch** [comment]
I'll close this without merging. I'd like to have a generic solution to restart the web server, no matter if it's apache or nginx, and also independent from the app type you're using.

**Comment by swrobel** [comment]
Ok, I'll leave that one to you guys...

**Pull request closed without merging**
