### PR TITLE
Fix bizarre error when “configuring” multiple PHP Apps

### LINKED ISSUE #76: Multiple PHP Apps fails on configure
Leaving the "DocumentRoot" empty.

DocumentRoot <%= @params[:docroot] %>

PS: I fixed and I will send a pull request next.
PS 2: Support Case ID 123158551

### PR DESCRIPTION
**Pull request by arielpts**
Leaving the "DocumentRoot" empty.

DocumentRoot <%= @params[:docroot] %>

PS: Support Case ID 123158551

Fixes #76

### CODE REVIEW

**Comment by jweiss** [comment]
Can you please share a bit more background on this?

Also, the include_attribute should probably go to the top of the file?

**Comment by arielpts** [comment]
@jweiss Sorry, I just assumed that you had access to the support cases. My bad.

I moved the include attribute to the top of the file: https://github.com/ebanx/opsworks-cookbooks/commit/2bbe098750131dc3ac47095403f46145929775f8

The problem is that the recipie mod_php5_apache2::php uses the variable deploy[:absolute_document_root] to set the docroot, however, the :absolute_document_root is only set on the deploy/attributes/deploy.rb file, thus causing the error in the configure livecycle event.

The full explanation (provided in the support case ID 123158551):

Sometimes when i'm deploying a PHP app in my stack with multiple apps, all other's apps virtual hosts configurations is rendered with a empty @params[:docroot]

For instance, when i'm deploying xxx, sometimes the virtualhosts for yyy is rendered with the variable for DocumentRoot and Directory empty!

This file is rendered
https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/mod_php5_apache2/templates/default/web_app.conf.erb#L6

The variable: @params[:docroot]

Steps to reproduce:
1) Deploy some app.
2) The virtual host file (/etc/apache/sites-enabled/xxxx.conf) of the 2 _others_ apps will have empty "DocumentRoot" and empty "Directory".

---- Begin output of sleep 1 && /etc/init.d/apache2 restart && sleep 1 ----
STDOUT: Action 'configtest' failed.
The Apache error log may have more information.
...fail!
STDERR: Syntax error on line 4 of /etc/apache2/sites-enabled/xxxxx.conf:
DocumentRoot takes one argument, Root directory of the document tree
---- End output of sleep 1 && /etc/init.d/apache2 restart && sleep 1 ----

**Comment by awsrequena** [comment]
Sorry, we didn't posted any feedback here since your last comment.

We're testing/verifying your pull request. The fix should be available soon.

In the meanwhile you could easily fix this for you by delivering a custom cookbook "mod_php5_apache2" containing an attribute file "default.rb" which contains your fix.  The attribute file should be deep merged with the build in one, thus fixing the issue.

**Comment by arielpts** [comment]
Thanks for the feedback @awsrequena.

I know that I can do that, however I really dislike this "fixes". I think this long process to merge discourages opensource contributions. I have others "fixes" done (for other things) that I have very little desire to create a pull request.

Anyway, thanks for the feedback.

**Comment by awsrequena** [comment]
I can really understand you, we've neglected this very important feedback channel in the past.  I can assure you that this is changing. 

Please don't feel discouraged to give feedback, it's very valuable and we need this to make our service more suitable for you.

Some feedback to you pull request. First of all, thank you very much for pointing this out. The fix you proposed, will repair the failure, but the actual problem here is, that OpsWorks will trigger a deployment of the PHP application on your instance during a 'configure' life cycle event. This is should not happen, during a 'configure' LCE only a reconfiguration of the application should happen, if necessary. So the fix is a bit more complex and must be done in another context.

I'll inform you when this is deployed.

**Comment by awsrequena** [comment]
The fix for this problem was just deployed.  The mod_php5_apache2 recipe will not be executed during configure.

**Comment by arielpts** [comment]
Thank you VERY much, @awsrequena!!

**Pull request closed without merging**
