### PR TITLE
Mongo DB Updates for OpsWorks and Amazon Linux Support

### PR DESCRIPTION
**Pull request by Cyclic**
This is the mongo db support from edelight, but with a working instance for a custom Amazon Linux OpsWorks layer. As of testing, the OpsWorks support for a single instance is now working, and the instructions are included in an updated readme file in the root of the repo. The main changes that got the single node instance working involve making changes to the chef script that allow it to work with chef 9, the addition of the mongod.conf template for the service to work correctly with Amazon Linux, and the addition of the journal path link creation to point to the journal volume instead of just having mongo create it in the data volume (this is outlined in the Mongo DB docs regarding EC2 setup for Mongo DB). Any other code changes from the edelight version are likely cosmetic. The only other addition from the edelight version is the recipe that removes the 10gen repo (see readme for details).

### CODE REVIEW

**Comment by jbraeuer** [comment]
Hi,
could you please send this pull request against the example repo https://github.com/amazonwebservices/opsworks-example-cookbooks? At this point in time adding this to the examples seems to be the better choice.
Happy to merge it there.

**Comment by thom-nic** [comment]
Was this merged anywhere?  I don't see it in amazonwebservices/opsworks-example-cookbooks

**Comment by Cyclic** [comment]
I'm not sure, but most of the changes had to do with the fact that AWS didn't use Chef 11 at the time. Now that Chef 11 is supported, the main edelight repo should probably be used. I can see about testing this out next month with the drive mappings. It's probably best if I reform the example cookbooks, and then put the edelight version into a directory that forks the main so changes/updates can get propagated automatically between both repositories; however, this is a bit beyond my current GIT knowledge, so I will need to dig. If you know what the commands are, or would like to run them -- please let me know. I will dig in if I don't hear back. By the way, these patches still work with the latest OpsWorks.

Thanks!

**Comment by Cyclic** [comment]
Lots of activity here: https://github.com/edelight/chef-mongodb so I'll have to give it a shot to see if it just works. If so, it might make sense to see if Amazon can do something to merge the primary repo into the opsworks examples rather than have me as a middleman. :)

**Pull request closed without merging**
