### PR TITLE
Adds blank metadata.rb files to cookbooks missing them

### PR DESCRIPTION
**Pull request by jpslav**
Howdy,

Though I can't find an explicit requirement that `metadata.rb` files are required, the Opscode site says:

> Every cookbook requires a small amount of metadata. Metadata is stored in a file called metadata.rb that lives at the top of each cookbook’s directory.
> _http://docs.opscode.com/essentials_cookbook_metadata.html_

I'm using Berkshelf to model my AWS OpsWorks environments with Vagrant, and Berkshelf takes the above statement to heart and validates a cookbook by checking for the existence of the `metadata.rb` file.  

Seems to me that since y'all have these files in some cookbooks already, there'd be no problem adding blank `metadata.rb` files where they are missing.  That is what I have in this PR.  I chose to add blank versions of these files because I thought that may make it trivial for y'all to merge this.

Note that #6 discusses some of these same issues, as does #8.  Those PRs have been around a while with not much action, so I'm hoping that less code (actually _no code at all_) in this PR makes it an easier call for AWS folks.

### CODE REVIEW

**Comment by jbraeuer** [comment]
Thanks for your pull request. We will introduce this code as part of the ongoing work to support newer version of Chef.

**Comment by jamesonjlee** [comment]
@jbraeuer I would love to see this get merged in, missing the metadata files makes it difficult to continue developing with opsworks.

**Comment by jschneiderhan** [comment]
@jbraeuer any chance on getting this merged soon? I use Berkshelf for cookbook development and cannot currently use it the way I want to because it refuses to pull in cookbooks without a metadata file.

**Comment by githuesch** [comment]
We are in the process of improving metadata for all cookbooks. We are making sure there's a proper metadata.rb in each cookbook, not just an empty one.

I will not merge the pull request, but I created a new commit.
The commit will be visible here, once the code is available in production.

**Comment by jbraeuer** [comment]
Closing the issue as @githuesch solved it.

**Comment by jpslav** [comment]
Howdy -- see that this was indeed fixed in the chef 11 branches, but for those of us who joined opsworks in the chef 0.9 era, can the `release-chef-0.9` branch be updated as well?

**Pull request closed without merging**
