### PR TITLE
Update customize.rb

### PR DESCRIPTION
**Pull request by mattctaylor**
Deploy sites to EBS volume at /mnt/www

### CODE REVIEW

**Comment by shlomoswidler** [comment]
Doesn't this belong in deploy.rb? customize.rb is meant to be a hook to allow overriding attributes in custom cookbooks.

**Comment by mattctaylor** [comment]
Yes probably. I'm new to this. I'm just trying to find a way for
applications to deploy to a mounted EBS volume rather than the default
/srv/www.

I couldn't get it working so I closed the update.

**Comment by shlomoswidler** [comment]
That's a good question. I would just mount the EBS volume at /srv/www .

**Comment by mattctaylor** [comment]
Yeah I tried that but unfortunately it's not allowed. /srv/www is reserved
by Opsworks.

Matt Taylor
Director | Yamo
Direct: 02 8488 3230 | Fax: 03 6165 0552
Support: support@yamo.com.au | 02 8244 0003

**Comment by awsrequena** [comment]
@mattctaylor you can see how this is put together in `opsworks_initial_setup/attributes/default.rb`

You can do this in different ways.  You could change the EBS volume used to mount directories that should be persisted, but will change the used device for every "mounted" directory.  The attribute used for this is called `node[:opsworks_initial_setup][:ephemeral_mount_point]`.

Or you could overwrite the attribute `default[:opsworks_initial_setup][:bind_mounts][:mounts]` via customize.rb. IMPORTANT: This is a hash, so please keep in mind that the default keys are expected in the cookbooks. 

If you want to follow the logic behind it see:
- opsworks_initial_setup/attributes/default.rb
- opsworks_initial_setup/recipes/bind_mounts.rb
- opsworks_initial_setup/recipes/autofs.rb
- opsworks_initial_setup/templates/default/automount.opsworks.erb

**Comment by mattctaylor** [comment]
Thanks I got it working!

Matt Taylor
Director | Yamo
Direct: 02 8488 3230 | Fax: 03 6165 0552
Support: support@yamo.com.au | 02 8244 0003

**Pull request closed without merging**
