### PR TITLE
Add X-Request-Start header for NewRelic request queuing reporting

### PR DESCRIPTION
**Pull request by swrobel**
This enables NewRelic request queueing reporting for nginx/unicorn webapps. See https://docs.newrelic.com/docs/features/request-queue-server-configuration-examples#nginx

My contribution is provided under the Apache 2.0 license.

### CODE REVIEW

**Comment by swrobel** [comment]
Should be clean to merge into master-chef-11.10 as well

**Comment by cbbarclay** [comment]
Thank you, we will review your pull request.

**Comment by githuesch** [comment]
I merged your request locally. It will show up here as soon as we roll this change out with a new agent. Thanks again for your contribution.

**Comment by githuesch** [comment]
We just removed this again as it's not supported by nginx 1.1.19, the version we have on Ubuntu instances.

**Comment by swrobel** [comment]
Updated to check platform and not apply this on ubuntu instances

**Comment by swrobel** [comment]
@githuesch this PR was is updated to address your issue. Why no action?

**Comment by cbbarclay** [comment]
Thank you, we will review your pull request update.

**Comment by awsrequena** [comment]
We should be able to include custom headers and not just set default headers, this may not work or not be wanted/needed by other customers.

**Comment by swrobel** [comment]
@awsrequena in an ideal world, I agree with you, but this is a relatively benign header and is necessary for NewRelic and other performance monitoring tools to report request queuing.

**Pull request closed without merging**
