### PR TITLE
Support index.html and index.htm as default document

### PR DESCRIPTION
**Pull request by dreamwords**
Can you please review the below patch to add default document for nginx unicorn app? Thanks.

### CODE REVIEW

**Comment by githuesch** [comment]
Can you please explain in detail what's the problem you're trying to fix with this change?

**Comment by dreamwords** [comment]
1) There's default document like "index.html" or "index.htm" in the public (document root)
2) There's no default index action in the Rails application

Which causes that

When the user tried to access "www.test.com/"

Nginx throws the "/" to the unicorn (Rails application), and the user get a 404

If there are default documents "index.html", "index.htm", nginx should send back response directly.

**Comment by dreamwords** [comment]
githuesch, any comments on this?

**Comment by githuesch** [comment]
@dreamwords Sorry for the delay, I was a bit swamped with other things. I understand your change, but I was trying to think of situations where this behavior is not what you want. In particular, I wonder if there are cases where making this change could break a setup that relies on the version without your changes.

I'll discuss this internally and come back with an answer soon.

**Comment by dreamwords** [comment]
Thanks, githuesch.

I think there are mainly two concerns:

1) "try_files"

"try_files" directive appeared in nginx 0.7.27, if this will be a problem, let's use "if -f" directive.

2) "index.html" as default document

Please keep me posted. Thanks again!

**Comment by workeitel** [comment]
@dreamwords - can you please explicit confirm that your contribution ist licensed under the Apache 2.0 license?

**Comment by dreamwords** [comment]
confirmed.

Best Regards,

-Elan Meng

**Comment by workeitel** [comment]
Thanks for your contribution. We decided to use your improvement in our cookbooks. We will merge this to our repository and the changes will appear here as so as the code gets to production. I will leave this pull request open for this time and close it when we release the new version.

**Comment by dreamwords** [comment]
Great. Thanks!

**Comment by workeitel** [comment]
Now your contribution is finally in production. Thanks again.

**Pull request closed without merging**
