### PR TITLE
Quick Fixes for PHP Cookbook

### PR DESCRIPTION
**Pull request by mikegreiling**
- Remove php closing tag along with trailing whitespace which may cause premature output by certain PHP configurations.
- Declare $stack_name class variable
- Fix typo in php::configure debug message

### CODE REVIEW

**Comment by awsrequena** [comment]
The code looks good to me. Agree with merging it.

**Comment by githuesch** [comment]
LGTM as well.

**Comment by awsrequena** [comment]
@mikegreiling you agree to contribute this PR under the Apache License, version 2.0 [http://aws.amazon.com/apache2.0] )

**Comment by mikegreiling** [comment]
Yes, of course :)

**Comment by awsrequena** [comment]
Thanks

**Pull request merged**
