### PR TITLE
Added puma cookbook

### PR DESCRIPTION
**Pull request by moritzheiber**
This adds puma as an alternative to configure with nginx as an
app preprocessor for Rails applications.

Also see https://www.engineyard.com/articles/rails-server for
why this is a good idea.

### CODE REVIEW

**Comment by moritzheiber** [comment]
This is largely untested as I lack a proper development environment. It's also a mere copy of most of the unicorn cookbooks' definitions. 

I'd be happy to answer question and adjust the request though.

**Comment by cbbarclay** [comment]
Thank you, we will review your pull request.

**Comment by ujuettner** [comment]
Please confirm that we accept your contribution under the Apache 2.0 license.

**Comment by moritzheiber** [comment]
Yes, I hereby confirm that my contribution is under Apache 2.0 license.

**Comment by swrobel** [comment]
:+1:

**Comment by StupidCodeFactory** [comment]
:+1:

**Comment by evanphx** [comment]
Speaking as the @puma author, anything I can do to help get this merged?

**Comment by matthewrudy** [comment]
I'm happy to be guinea pig on this.

**Comment by githuesch** [comment]
@moritzheiber You mentioned that this code is largely untested as you lack a proper development environment. I tried this out and ran into a few errors right away. After fixing them I ran into more errors.
So my guess is that you didn't really run this cookbook on OpsWorks, or against any Chef server for that matter. Don't get me wrong, I'm not pointing fingers. Testing cookbooks on OpsWorks isn't very convenient yet. We're working on this, bear with us!

With the introduction of support for Chef 11.10 we changed the override behavior for cookbook contents. This makes it a lot easier to prepare pull requests because you can now simulate how a new cookbook would work on OpsWorks if we added it to our built-in cookbooks. You can read up on the details here: http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-chef11-10.html#workingcookbook-chef11-10-override. But what it boils down to is that whatever you put in your custom cookbooks overwrites what's in our built-in ones. That's potentially dangerous, but in your case it's exactly what you need.

Here's how you can make sure your cookbook works.
- Set up an OpsWorks stack with Chef 11.10.
- Add your puma cookbook to your custom cookbooks.
- When there are changes you need to make to existing files in our built-in cookbooks, replicate the directory structure, so directories are named exactly as they are in our built-in cookbooks, and then only create the files that you need to change; this is not a strict necessity, but you may have noticed that what you see on Github is not always what you will see on running instances. We're getting better at keeping those in sync, but by only putting the files that need to be changed into your custom cookbooks you reduce the probability of missing a change we made to one of the other files.
- Make an actual Rails app work with that cookbook on OpsWorks. You can use the stack's custom JSON to make sure your cookbook is used instead of nginx_unicorn.

``` json
{
  "opsworks": {
    "rails_stack": {
      "name": "nginx_puma"
    }
  }
}
```

Here are the problems I found so far.

``` diff
# without the following change, the 'apache' group would be used for the nginx_puma case
--- a/deploy/attributes/deploy.rb
+++ b/deploy/attributes/deploy.rb
@@ -41,7 +41,7 @@ case node[:platform]
 when 'debian','ubuntu'
   default[:opsworks][:deploy_user][:group] = 'www-data'
 when 'centos','redhat','fedora','amazon'
-  default[:opsworks][:deploy_user][:group] = node['opsworks']['rails_stack']['name'] == 'nginx_unicorn' ? 'nginx' : 'apache'
+  default[:opsworks][:deploy_user][:group] = node['opsworks']['rails_stack']['name'].include?('nginx') ? 'nginx' : 'apache'
```

``` diff
# syntax error
--- a/deploy/attributes/rails_stack.rb
+++ b/deploy/attributes/rails_stack.rb
@@ -29,7 +29,7 @@ when "nginx_unicorn"
 when "nginx_puma"
   default[:opsworks][:rails_stack][:recipe] = "puma::rails"
   default[:opsworks][:rails_stack][:needs_reload] = true
-  default[:opsworks]:rails_stack][:service] = 'puma'
+  default[:opsworks][:rails_stack][:service] = 'puma'
```

``` diff
# missing 'when' block for nginx_puma
diff --git a/deploy/definitions/opsworks_deploy.rb b/deploy/definitions/opsworks_deploy.rb
index fc2589c..5c91547 100644
--- a/deploy/definitions/opsworks_deploy.rb
+++ b/deploy/definitions/opsworks_deploy.rb
@@ -176,8 +176,14 @@ define :opsworks_deploy do
         deploy deploy
       end

+    when 'nginx_puma'
+      puma_web_app do
+        application application
+        deploy deploy
+      end
+
     else
      raise "Unsupport Rails stack"
```

``` diff
# Syntax error in the line with PID_PATH, you're using #{} outside a string literal; the other lines would actually work, but I still recommend reverting them to what you found in the original file in the unicorn cookbook for easier comparison
--- a/puma/templates/default/puma.service.erb
+++ b/puma/templates/default/puma.service.erb
@@ -3,9 +3,9 @@
 require 'etc'
 require 'digest/md5'

-ROOT_PATH=<%= @deploy[:deploy_to].inspect %>
-APP_NAME=<%= @application.inspect %>
-PID_PATH=<%= #{@deploy[:deploy_to]/shared/pids/puma.pid}.inspect %>
+ROOT_PATH="<%= @deploy[:deploy_to] %>"
+APP_NAME="<%= @application %>"
+PID_PATH="<%= @deploy[:deploy_to] %>/shared/pids/puma.pid"
```

Then there's one thing that @evanphx can probably explain best.
I noticed this difference between the original unicorn service script template and the copy for puma that @moritzheiber modified.

``` diff
--- unicorn/templates/default/unicorn.service.erb
+++ puma/templates/default/puma.service.erb
-def stop_unicorn
-  if unicorn_running?
-    if run_and_ignore_exitcode_and_print_command "kill -QUIT `cat #{PID_PATH}`"
+def stop_puma
+  if puma_running?
+    if run_and_ignore_exitcode_and_print_command "kill -TERM `cat #{PID_PATH}`"
```

We're currently using the QUIT signal for unicorn and @moritzheiber is using TERM for Puma. Is there an advantage of using TERM instead of QUIT here, or does it even have to be TERM for Puma?

**Comment by evanphx** [comment]
The thuroughest of comments, bravo @githuesch.

Per your last question, puma registers a handler on TERM but not QUIT. So thusly TERM will perform a graceful shutdown where as QUIT will result in a hard and immediate shutdown. Probably best to use TERM.

**Comment by moritzheiber** [comment]
What @evanphx said.

Apart from that, thank you @githuesch, I'll come back with an amended, properly tested changeset :)

(Probably won't be until next week though)

**Comment by moritzheiber** [comment]
@ujuettner @githuesch Finished the refactoring. Please take a look at it again!

The puma stack works for a simple rails app now, but it should work for pretty much any other app too.

**Comment by joe1chen** [comment]
+1 @ujuettner @githuesch What happened to this pull request?

**Comment by tomasmuller** [comment]
:+1: great work!
Question: does AWS OpsWorks have a release schedule?

**Pull request closed without merging**
