### PR TITLE
Update database.yml.erb

### PR DESCRIPTION
**Pull request by achempion**
may be need use custom encoding

### CODE REVIEW

**Comment by achempion** [comment]
@jbraeuer could you burn it too?

**Comment by achempion** [comment]
@ujuettner could you burn it?

**Comment by ujuettner** [comment]
As I'm not a native speaker: What do you mean by "burn it"? To delete this pull request or to merge it? Your change looks reasonable.

**Comment by achempion** [comment]
@ujuettner merge it; currently we cant define other encoding like utf8mb4 for example

**Comment by jweiss** [comment]
@achempion you can do it today by overriding the template, see http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-template-override.html

**Comment by achempion** [comment]
@jweiss see into recipe file pliz, we cant change encoding because it hardcoded
https://github.com/aws/opsworks-cookbooks/blob/master/rails/templates/default/database.yml.erb#L5

**Comment by jweiss** [comment]
@achempion you can override the template like I wrote which means you can have any content you like in it, independent of the recipe.

**Comment by achempion** [comment]
@jweiss ok, thank you, but changing database encoding connection with custom json may be very useful

**Comment by jweiss** [comment]
Sure, I'm just saying you can do it today without waiting for us to merge and release a new agent.

**Comment by jweiss** [comment]
Closing as this has been shipped.

**Pull request closed without merging**
