### PR TITLE
[Rails] Support pool option in database.yml

### PR DESCRIPTION
**Pull request by ziggythehamster**
I apologize for the ton of commits :)

Anyways, this simple change allows you to specify the database pool size for Rails apps in database.yml.

### CODE REVIEW

**Comment by jbraeuer** [comment]
There is support for database pool size on it's way - just to let you know.
I will look into the rest of your enhancements in the soon future.

**Comment by githuesch** [comment]
Support for database pool size is now available for customers using Chef 11.4.

**Comment by ziggythehamster** [comment]
GitHub unhelpfully won't let me change the branch to merge into, so it would normally tell me that this pull merged cleanly or something to that effect.

Feel free to close this if you're not going to backport it to 0.9.

**Comment by githuesch** [comment]
Thanks!

**Pull request closed without merging**
