### PR TITLE
Support custom log_format on nginx.

### PR DESCRIPTION
**Pull request by yalab**
Hi.
I wanted to use custom log format on unicorn-rails.
I try to support it.

Thanks.

### CODE REVIEW

**Comment by ujuettner** [comment]
Please confirm that we accept your contribution under the Apache 2.0 license.

**Comment by yalab** [comment]
@ujuettner I confirm Apache 2.0 licence. Do I have to change about your point?

**Comment by ujuettner** [comment]
Thanks for the confirmation. I'd go with my proposal to separate the custom log format definition and its usage, ok?
My changes will be under Apache 2.0 license, I asked for confirmation because all the changes are based on your ideas.

**Comment by ujuettner** [comment]
Thanks again a lot for your pull request. The fix has been merged. The commit will be visible in this repository, once the code made it in production.

**Pull request closed without merging**
