### PR TITLE
Remove runit cookbook

### PR DESCRIPTION
**Pull request by richid**
This cookbook is several years out of date and is not required any other cookbook in this repository. It [has been stated](https://forums.aws.amazon.com/thread.jspa?messageID=479343) in the forums that it should be not be used and will be deprecated in the future. I'm hoping we can remove this source of frustration for myself and others and let the users include runit if they need it.

### CODE REVIEW

**Comment by jbrook** [comment]
Yes. Please remove this old and seemingly unused cookbook! Not having community cookbooks work out-of-the-box is a serious barrier to Opsworks adoption.

**Comment by swrobel** [comment]
:+1:

**Comment by cbbarclay** [comment]
Thank you, we will review your pull request.

**Comment by awsrequena** [comment]
removed on the next major version of the opsworks agent.

thanks for the contribution

**Pull request closed without merging**
