### PR TITLE
Reconnect to Rails cache server after Unicorn forks

### PR DESCRIPTION
**Pull request by swrobel**
Should be safe to merge into master-chef-11.10 as well

My contribution is provided under the Apache 2.0 license.

### CODE REVIEW

**Comment by cbbarclay** [comment]
Thank you, we will review your pull request.

**Comment by githuesch** [comment]
You are calling `Rails.cache.reconnect` twice, once in the condition, and then inside the if block. Could it be you actually want to use something like `Rails.cache.respond_to?(:reconnect)`?

**Comment by swrobel** [comment]
According to the [docs](http://ruby-doc.org/docs/keywords/1.9/Object.html#method-i-defined-3F), defined? does not actually execute the expression passed to it, but maybe I'm misunderstanding something.

**Comment by githuesch** [comment]
No, you're right. I didn't know this. Thanks for the pointer.
But still, this doesn't look idiomatic to me.

**Comment by githuesch** [comment]
@swrobel How did you test this? Did you run into an error I could reproduce first before incorporating this change?

**Comment by swrobel** [comment]
If you are using redis-store as the Rails cache store with Unicorn it will error out when it forks because it can't reuse the cache connection.

**Comment by githuesch** [comment]
Sure, a concrete example app would have been helpful, but I guess I can just adapt a demo app.

**Comment by githuesch** [comment]
I deployed a Rails app that uses redis-store. Works fine with unicorn, without your change.

When you can give me an app that exposes the problem you're describing, I'm happy to revisit this request, but I don't want to make a change to fix a problem I can't reproduce.

**Comment by swrobel** [comment]
Can you point me to the code for the app?

**Comment by githuesch** [comment]
Sure, here you go: https://github.com/wuputah/redis-example.

**Comment by swrobel** [comment]
Ok, it looks like the reason you weren't seeing it was that example is using Rails 3.0.x which requires using the redis gem 2.x. The check for connection reuse from forked processes was added in redis 3.x. Good news is it seems this was fixed and redis will auto-reconnect from a forked process like dalli does so this should become unnecessary as of the next release of the redis gem!

https://github.com/redis/redis-rb/pull/414

**Comment by githuesch** [comment]
Glad to hear that, thanks for the update.

**Pull request closed without merging**
