### PR TITLE
Add port support to database.yml

### PR DESCRIPTION
**Pull request by seangaffney**

### CODE REVIEW

**Comment by ziggythehamster** [comment]
One of us should merge this with #19 so that AWS only has one pull request to pull in for this file.

**Comment by seangaffney** [comment]
Since mine can only be an integer, does it really need to be escaped?

**Comment by ziggythehamster** [comment]
Not really, but this merge and my merge won't merge together cleanly and I was hoping to make it simpler on the OpsWorks team to get both our changes in :)

**Comment by jbraeuer** [comment]
This feature was added in https://github.com/aws/opsworks-cookbooks/commit/df634dfe84e39e65be8fb220c3fd28590b3823eb

Thanks for you pull request.

**Pull request closed without merging**
