### PR TITLE
Apache should be configured using the given group from the attributes on Ubuntu 14.04 as well

### PR DESCRIPTION
**Pull request by c-styles**
related commit 57745aed2eee8de4aa95615a7e6280c4d519aaca

### CODE REVIEW

**Comment by awsrequena** [comment]
You're totally right! thanks for the hint.

**Comment by awsrequena** [comment]
In order to accept your PR, you need to agree that your contribution is licensed under the Apache License version 2.0

**Comment by c-styles** [comment]
@awsrequena Yes, of course :)

**Comment by githuesch** [comment]
This is in production now. Thanks again for your contribution.

**Comment by c-styles** [comment]
https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.10/apache2/templates/ubuntu-14.04/envvars.erb#L17

> This is in production now.  Thanks again for your contribution.

This is still using user for apache run group. It looks like this file hasn't change. Is this envars no longer using for ubuntu 14.04?

**Comment by githuesch** [comment]
I mixed this up with a similar pull request, sorry for the confusion.

**Comment by githuesch** [comment]
Your change will be included in an upcoming release.

**Comment by c-styles** [comment]
Thanks! :)

**Comment by c-styles** [comment]
Just for remind, this fix is noticed at mod php apache2 env.

**Comment by c-styles** [comment]
Checked latest release and works fine!
Thanks. I closed this pull request

**Pull request closed without merging**
